# Generated by Django 4.1.7 on 2023-04-13 21:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='migrateGoshDangIt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_migrated', models.DateField(blank=True, default=datetime.datetime.today)),
            ],
        ),
        migrations.CreateModel(
            name='missingPersons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_missing', models.DateField(blank=True, default=datetime.datetime.today)),
                ('first_name', models.CharField(max_length=10)),
                ('last_name', models.CharField(max_length=15)),
                ('age_at_missing', models.IntegerField(default=0)),
                ('city', models.CharField(max_length=16)),
                ('state', models.CharField(max_length=2)),
                ('gender', models.CharField(max_length=50)),
                ('race', models.CharField(max_length=1)),
            ],
        ),
    ]
