# Generated by Django 4.1.7 on 2023-04-13 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basefolder', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='migrateGoshDangIt',
        ),
    ]
